# Generated by Django 3.2.16 on 2023-01-31 14:31

import blog.helper
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='')),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(upload_to=blog.helper.object_directory_path, verbose_name='Main Image')),
                ('is_publish', models.BooleanField(default=True, verbose_name='Publish')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='create')),
                ('published', models.DateTimeField(auto_now=True, verbose_name='publish')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='update')),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
