# Generated by Django 3.2.16 on 2023-01-31 14:43

import blog.helper
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230131_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='create'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='d', upload_to=blog.helper.object_directory_path, verbose_name='Main Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='is_publish',
            field=models.BooleanField(default=True, verbose_name='Publish'),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.DateTimeField(auto_now=True, verbose_name='publish'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='d', max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='update'),
            preserve_default=False,
        ),
    ]
