# Generated by Django 3.2.16 on 2023-01-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230131_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='d', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
