# Generated by Django 3.2.16 on 2023-01-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_publish',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
        migrations.AddField(
            model_name='post',
            name='release',
            field=models.DateTimeField(auto_now=True, verbose_name='release'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pu', 'Publish'), ('dr', 'Draft')], default=('dr', 'Draft'), max_length=25, verbose_name='Post status'),
        ),
    ]
